language: cpp
dist: xenial
git:
  depth: 1
before_install:
- echo 'Installing ARM toolchain'
- ls
- wget https://developer.arm.com/-/media/Files/downloads/gnu-a/9.2-2019.12/binrel/gcc-arm-9.2-2019.12-x86_64-aarch64-none-elf.tar.xz
- tar -Jxvf  gcc-arm-9.2-2019.12-x86_64-aarch64-none-elf.tar.xz
- export PATH=$(pwd)/gcc-arm-9.2-2019.12-x86_64-aarch64-none-elf/bin:$PATH
- echo $PATH
- chmod +x build_all.sh
- chmod +x build_circle.sh
- chmod +x build_pi3.sh
- chmod +x build_pi4.sh
script:
- "./build_all.sh"
- tar -czvf sugarpi.gz $(pwd)/sdcard

deploy:
  provider: releases
  api_key:
    secure: CoqX6BaEB6iKjPe+dkN3jhqUcmxc16kzgMes5oBPMzk3Ha5zfenIQj0mK1A/c6pUn2CFyeEgGQU/RG6ETINMW7Y2VVdwl45qOaqWzKRNHC1ihIkLwZxBrXVB/QSac897UIQoezU+7bhMH+j5c0QNfOuhCaDVyr2gYseF5OZX0g69c43qJseK+jHZ562hXvcqXXcDUpGWkxAL/Lzb0bJZcbl9e2LhOJidmwAhH2xBhSdWAK3JuHCzwYtVVQ8Nv4fxClkcI85z+X4e8I2gSUP0g3VivtxS/lAyO6QBnkqcWW3mXaFLjFeeVi2ofMthmri+HwbJr9qs7dTMvXm93V6023Q6Qd1TKITVMUtIlpiV1kFGfyyiKWGmTTumuv0QTfjSn8jOCYCgamFZCJrakz5U4DM69rQ3hiHwmvRJWncKUHjxJlW6/LK/83XVr8wRYZRlCk/YqPp8TBNu97QnNsAQqaS8ZrLe/o1qyhnslTnzcT6k21HQlXuOWp2MLuSDacKLdG5w1MLXnpD3BJWogcqTsTotnTZvFMa6asB6BBvnSVoRYm8bWc6rcor8478b8G+1AtQvG7wCBKtKvR4qnXkJ3l2vuq71iY1LNKfQ0/2r+/6imggbYxzdz/3sDWNxjlWH54qsFlrDaYTdAc3/V+LK0OC/z63OezGibQj/aTk3Nwg=
  file: sugarpi.gz
  on:
    repo: Tom1975/SugarPi
  skip_cleanup: 'true'
