//{{NO_DEPENDENCIES}}
// fichier Include Microsoft Visual C++.
// Utilisé par ConfigKeyboard.rc
//
#define IDC_MYICON                      2
#define IDOK2                           2
#define ID_CANCEL                       2
#define IDOK3                           3
#define ID_APPLY                        3
#define IDR_DISK                        4
#define IDD_SET_SCAN                    101
#define IDD_SUGARBOX_DIALOG             102
#define IDD_SET_SCAN1                   102
#define IDD_PRESSAKEY                   102
#define IDS_APP_TITLE                   103
#define IDD_ABOUTBOX                    103
#define IDM_ABOUT                       104
#define IDC_SUGARBOXCLIENT              104
#define IDM_EXIT                        105
#define IDI_SUGARBOX                    107
#define IDI_SMALL                       108
#define IDC_SUGARBOX                    109
#define IDR_MAINFRAME                   128
#define IDD_DIALOG1                     129
#define IDD_SETTINGS                    129
#define IDD_CFG_CPC                     130
#define IDD_CFG_SOUND                   131
#define IDD_CFG_KEYBOARD                132
#define IDB_KEYB                        132
#define IDB_KEYB_EN                     133
#define IDD_CFG_JOY                     133
#define IDB_KEYB_ES                     134
#define IDD_CFG_ROM                     134
#define IDB_KEYB_FR                     135
#define IDD_CFG_GEN                     135
#define IDB_KEYB_MASK                   137
#define IDD_SAVE_CFG_AS                 139
#define IDI_ICON3                       142
#define IDI_RECORD_OFF                  142
#define IDB_RECORD_ON                   157
#define IDB_SOUND_OFF                   158
#define IDB_SOUND_ON                    159
#define IDB_BITMAP1                     161
#define IDB_RECORD_OFF                  161
#define IDB_PNG1                        167
#define IDB_PNG2                        168
#define IDB_PC                          169
#define IDB_BP                          170
#define IDB_BP_DIS                      171
#define IDB_PNG4                        171
#define IDB_PNG3                        172
#define IDB_BITMAP2                     173
#define IDB_PNG5                        175
#define IDB_PNG6                        176
#define IDB_BITMAP3                     177
#define IDB_PNG7                        177
#define IDB_BITMAP4                     178
#define IDB_PNG8                        178
#define IDR_MENU1                       179
#define IDB_PNG9                        179
#define IDB_PNG10                       180
#define IDD_POKE                        180
#define IDB_PNG11                       181
#define IDB_PNG12                       182
#define IDB_PNG13                       183
#define IDB_PNG14                       184
#define IDB_PNG15                       185
#define IDD_SELPOSTAPE                  186
#define IDD_DIALOG2                     187
#define IDD_EXT_LIB                     187
#define IDD_INET_SETTINGS               188
#define IDD_DIALOG3                     189
#define IDD_WAIT                        189
#define IDD_SEND_SIGNAL                 190
#define IDD_DIALOG4                     191
#define IDD_SELECTDISPLAY               191
#define IDR_WAVE_DISK_INSERT            193
#define IDR_WAVE_DISK_EJECT             194
#define IDD_DEBUGGERDLG                 194
#define IDR_WAVE_DISK_RUN               195
#define IDB_BITMAP5                     195
#define IDB_KEYB_DA                     195
#define IDD_DEBUGGERDLG1                195
#define IDD_MEMDBG                      195
#define IDR_WAVE_DISK_TRACK_CHG_SHORT   196
#define IDD_DEBUGGERDLG2                196
#define IDD_CDTCDBGDLG                  196
#define IDR_WAVE_DISK_TRACK_CHG_LONG    197
#define IDD_SETTINGS_EMULATOR           197
#define IDB_FLAG                        198
#define IDB_PNG16                       200
#define IDB_SKIN_LEFT                   204
#define IDB_BITMAP6                     205
#define IDB_SKIN_MIDDLE                 206
#define IDB_BITMAP8                     207
#define IDB_SKIN_RIGHT                  207
#define IDB_BITMAP7                     208
#define IDB_LOAD_DISK                   208
#define IDR_MENU2                       209
#define IDR_MEMEDITOR                   209
#define IDI_SUGARBOX_                   210
#define IDB_SPLASHSCREEN                212
#define IDB_BITMAP9                     213
#define IDB_SUGARBOX_ABOUT              213
#define IDC_TAB1                        1000
#define IDC_RADIO1                      1001
#define IDC_RADIO2                      1002
#define IDC_RADIO3                      1003
#define IDC_RADIO4                      1004
#define IDC_RADIO5                      1005
#define IDC_MONO                        1006
#define IDC_RADIO_HARD_1                1006
#define IDC_STEREO                      1007
#define IDC_RADIO_HARD_2                1007
#define IDC_COMBO_OUTPUT                1008
#define IDC_RADIO_HARD_3                1008
#define IDC_16BPS                       1009
#define IDC_RADIO_HARD_4                1009
#define IDC_8BPS                        1010
#define IDC_RADIO10                     1010
#define IDC_RADIO_HARD_5                1010
#define IDC_44                          1011
#define IDC_22                          1012
#define IDC_125                         1013
#define IDC_COMBO1                      1015
#define IDC_SAVEAS                      1017
#define IDC_BMP_KEYB_FR                 1018
#define IDC_EDIT1                       1019
#define IDC_LINE                        1019
#define IDC_EDIT2                       1020
#define IDC_BIT                         1020
#define IDC_EDIT3                       1021
#define IDC_SCAN                        1021
#define IDC_EDIT4                       1022
#define IDC_EDIT5                       1023
#define IDC_EDIT6                       1024
#define IDC_LIST1                       1027
#define IDC_BUTTON1                     1028
#define IDC_NEW                         1028
#define IDC_BUTTON2                     1029
#define IDC_CLOSE                       1029
#define IDC_INFORMATIONS                1030
#define IDC_BUTTON4                     1030
#define IDC_CLEARCACHE                  1030
#define IDC_POSTAPE                     1031
#define IDC_BUTTON5                     1031
#define IDC_POSTAP                      1032
#define IDC_BUTTON3                     1032
#define IDC_BUTTON6                     1032
#define IDC_STATIC2                     1033
#define IDC_BUTTON7                     1033
#define IDC_SCR1                        1034
#define IDC_SCR2                        1035
#define IDC_DSK_ST1                     1036
#define IDC_DSK_ST2                     1037
#define IDC_DSK_ST3                     1038
#define IDC_DSK_ST4                     1039
#define IDC_CHECK_AMSTRADEU             1040
#define IDC_CHECK_CPCPOWER              1041
#define IDC_CHECK3                      1042
#define IDC_CHECK_PROXY                 1042
#define IDC_AUTODETECT                  1043
#define IDC_PROXY_SERVER_LIST           1044
#define IDC_PROXY_BYPASS_LIST           1045
#define IDC_STATIC1                     1046
#define IDC_STATIC3                     1047
#define IDC_STATIC4                     1048
#define IDC_SETTINGS                    1049
#define IDC_RELOAD                      1050
#define IDC_SEND                        1051
#define IDC_SEL_DISPLAY                 1052
#define IDC_SEL_RES                     1053
#define IDC_CHECK1                      1054
#define IDC_BUTTON8                     1055
#define IDC_CHECK2                      1055
#define IDC_MULTIFACE2                  1055
#define IDC_BUTTON9                     1056
#define IDC_PLAYCITY                    1056
#define IDC_STATIC_DESCRIPTION          1057
#define IDC_BUTTON10                    1058
#define IDC_STATIC_CRTC_TYPE            1058
#define IDC_BUTTON11                    1059
#define IDC_BUTTON_CHOOSE_CART          1059
#define IDC_EDIT_CART_PATH              1060
#define IDC_STATIC_DEF_CART             1061
#define ID_DISK_DRIVE1                  32771
#define ID_DISK_DRIVE2                  32772
#define ID_DRIVE1_EJECT                 32773
#define ID_DRIVE1_INSERT                32774
#define ID_DRIVE2_EJECT                 32775
#define ID_DRIVE2_INSERT                32776
#define ID_CONTROL_RESET                32777
#define ID_SETTINGS                     32779
#define ID_SETTINGS_GENERALCONFIGURATION 32780
#define ID_CONTROL_OFF                  32781
#define ID_SETTINGS_LOADCONFIGURATIONFILE 32782
#define ID_SETTINGS_SAVECONFIGURATIONAS 32783
#define ID_DRIVE1_FLIP                  32784
#define ID_DRIVE2_FLIP                  32785
#define ID_RECORD_SND                   32786
#define ID_EDIT_COLLER                  32787
#define ID_CONTROL_NOSPEEDLIMIT         32788
#define ID_CONTROL_LIMITSPEEDTOVBL      32789
#define ID_SETTINGS_SCANLINES           32790
#define ID_SOUND_MUTE                   32791
#define ID_DISPLAY_TAKESCREENSHOT       32792
#define ID_DISPLAY_SIZE                 32793
#define ID_SIZE_STANDARDSIZE            32794
#define ID_SIZE_BIGGER                  32795
#define ID_SIZE_FULL                    32796
#define ID_SPEED_50                     32797
#define ID_SPEED_100                    32798
#define ID_SPEED_150                    32799
#define ID_SPEED_200                    32800
#define ID_SPEED_400                    32801
#define ID_SPEED_MAXSPEED               32802
#define ID_FILE_LOADSNAPSHOT            32803
#define ID_FILE_SAVESNAPSHOT            32804
#define ID_FILE_QUICKLOADSNAPSHOT       32805
#define ID_FILE_QUICKSAVESNAPSHT        32806
#define ID_FILE_QUICKSAVESNAPSHOT       32807
#define ID_TOGGLE_MAX_SPEED             32808
#define ID_SPEED_TOGGLEMAX              32809
#define ID_DRIVE_SAVEAS                 32810
#define ID_DRIVE2_SAVEAS                32811
#define ID_DRIVE1_SAVEAS                32812
#define ID_DRIVE2_SAVEAS32813           32813
#define ID_INSERTBLANKDISK_VENDOR_1     32814
#define ID_INSERTBLANKDISK_DATA_1       32815
#define ID_INSERTBLANKDISK_VENDOR_2     32816
#define ID_INSERTBLANKDISK_DATA_2       32817
#define ID_DEBUGGER_SHOWDEBUGGER        32818
#define ID_TAPE_RECORD                  32819
#define ID_TAPE_PLAY                    32820
#define ID_TAPE_REWIND                  32821
#define ID_TAPE_FASTFORWARD             32822
#define ID_TAPE_PAUSE                   32823
#define ID_TAPE_STOP                    32824
#define ID_TAPE_INSERTTAPE              32825
#define ID_TAPE_SAVEASWAV               32826
#define ID_TAPE_SAVSASCDT               32827
#define ID_TAPE_SAVEASCDT               32828
#define ID_TAPE_SAVEASCSW_11            32829
#define ID_DEBUGGER_POKE                32830
#define ID_TAPE_SAVEASCSWV2             32831
#define ID_TAPE_SAVEASCSW_V2            32832
#define ID_TAPE_SAVEASCDT_CSW           32833
#define ID_DRIVE_TOGGLEPROTECTION       32834
#define ID_DRIVE_TOGGLEPROTECTION_2     32836
#define ID_DISPLAY_FULLSCREENON         32837
#define ID_TAPE_POLARITY                32838
#define ID_SPEED_SYNC                   32839
#define ID_DISPLAY_INSERTBLACKFRAME     32840
#define ID_ONLINELIBRARIES_CPC          32841
#define ID_ONLINELIBRARIES_NETWORKSETTINGS 32842
#define ID_CONTROL_PAUSEEMULATION       32843
#define ID_FILE_LOADSCENARIO            32844
#define ID_FILE_RECORDSCENARIO          32845
#define ID_FILE_STOPREPLAYINGSCENARIO   32846
#define ID_FILE_STOP_RECORD             32847
#define ID_FILE_STOP_REPLAY             32848
#define ID_DISPLAY_CONFIGUREFULLSCREEN  32849
#define ID_DEBUGGER_STEP                32850
#define IDID_DBG_STEP_DEBUGGER_STEP     32851
#define ID_DBG_STEP                     32852
#define ID_DBG_STEPIN                   32853
#define ID_DBG_BREAK                    32854
#define ID_DBG_RUN                      32855
#define ID_DEBUGGER_DEBUGGERWINDOWS     32856
#define ID_DEBUGGERWINDOWS_MEMORY       32857
#define ID_MEMORY_MEMORY1               32858
#define ID_MEMORY_MEMORY2               32859
#define ID_MEMORY_MEMORY3               32860
#define ID_MEMORY_MEMORY4               32861
#define ID_EDIT_AUTORUNDISKINSERTED     32862
#define ID_TAPE_FASTLOAD                32863
#define ID_NO_SKINS                     32864
#define ID_DISPLAY_TAKESCREENSHOT_EVERY_FRAME 32885
#define ID_PLUGGEDDEVICE_MULTIFACESTOP  32886
#define ID_PLUGGEDDEVICE_MULTIFACEVISIBLE 32887
#define ID_CONTEXTMENU_COPY             32888
#define ID_CONTEXTMENU_PASTE            32889
#define ID_CONTEXTMENU_EXTRACTTOFILE    32890
#define ID_CONTEXTMENU_FILL             32891
#define ID_DEBUGGERWINDOWS_CRTC         32892
#define ID_SELECT_CONFIG_TOOLBAR        32893
#define ID_SETTINGS_EMULATORSETTINGS    32894
#define ID_CONTEXTMENU_MARKAS           32895
#define ID_MARKAS_DATA                  32896
#define ID_MARKAS_GRAPHICS              32897
#define ID_MARKAS_CODE                  32898
#define ID_MARKAS_                      32899
#define IDC_STATIC                      -1

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NO_MFC                     1
#define _APS_NEXT_RESOURCE_VALUE        214
#define _APS_NEXT_COMMAND_VALUE         32900
#define _APS_NEXT_CONTROL_VALUE         1062
#define _APS_NEXT_SYMED_VALUE           110
#endif
#endif
