name: C/C++ CI

on:
  push:
    branches: [ master, develop ]
  pull_request:
    branches: [ master, develop ]
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Checkout submodules
        run: git submodule update --init --recursive     
          
      - name: Set circle as writable
        run: |
          sudo chown -R $USER:$USER $(pwd)
          ls circle
          ls circle/boot
        shell: bash
        working-directory: .
        
      - name: Prepare SD Card
        run: |
          mkdir sdcard  
        shell: bash
        working-directory: .
      
      - name: Build Pi
        uses: ./sugarpi-action
        id:  buildpi
  
      - uses: actions/upload-artifact@v2
        with:
          name: SugarPi
          path: sdcard/*
